#!/bin/bash
set -e

VERSION=v0.0.1
BASE_BINARY_NAME=partner-charts-ci

cd $(dirname $0)

if [[ -f ../bin/${BASE_BINARY_NAME} ]]; then
    exit 0
fi

rm -rf ../bin
cd ..

mkdir -p bin
ARCH=$(go version | cut -d' ' -f4 | cut -d'/' -f1)
if [[ ${ARCH} == "linux" ]]; then
    BINARY_NAME=${BASE_BINARY_NAME}-${ARCH}-amd64
elif [[ ${ARCH} == "darwin" ]]; then
    BINARY_NAME=${BASE_BINARY_NAME}-${ARCH}-universal
else
    BINARY_NAME=${BASE_BINARY_NAME}-${ARCH}
fi
curl -s -L -o bin/${BASE_BINARY_NAME} https://github.com/samuelattwood/partner-charts-ci/releases/download/${VERSION}/${BINARY_NAME}
if ! [[ -f bin/${BASE_BINARY_NAME} ]] || [[ $(cat bin/${BASE_BINARY_NAME}) == "Not Found" ]]; then 
    rm bin/${BASE_BINARY_NAME}
    
    # Fall back to old process
    echo "Building binary locally..."
    rm -rf partner-charts-ci
    git clone --depth 1 https://github.com/samuelattwood/partner-charts-ci.git

    cd partner-charts-ci
    make
    mv bin ..
    cd ..
    rm -rf partner-charts-ci
else
    echo "${BINARY_NAME} => ./bin/${BASE_BINARY_NAME}"
fi

chmod +x ./bin/${BASE_BINARY_NAME}
